### ISSUE TITLE
Mixed fractions in ingredients not saving

### ISSUE THREAD

**Issue by leebickmtu** [matthiasclasen/gr#10]
I've noticed that when making a new recipe if I use a mixed fraction in an ingredient amount (ex. 1 1/2) it adds and shows correctly in the list upon clicking the "Add" button of the popover. However upon saving the recipe, any ingredient with mixed fractions is then missing.

Decimals work fine, like using "1.5" instead of "1 1/2". But I prefer the formatting and readability of the mixed fraction better.

**Comment by matthiasclasen** [comment]
oh, thanks for noticing this. Fixed now
