### ISSUE TITLE
App is crashing after clicking at "Buy Ingredients"

### ISSUE THREAD

**Issue by grousso** [matthiasclasen/gr#18]
Program received signal SIGSEGV, Segmentation fault.
gr_recipe_store_add_to_shopping (self=self@entry=0x1d1a920, recipe=0x1d69210, 
    serves=4) at gr-recipe-store.c:1536
1536	        for (i = 0; self->shopping[i]; i++) {

**Comment by matthiasclasen** [comment]
Sorry, should be fixed now. I pushed a newer flatpak build with the fix

**Comment by grousso** [comment]
Thank you! 
Everything is running smoothly now.
