### ISSUE TITLE
Something is wrong with the repo today

### ISSUE THREAD

**Issue by grousso** [matthiasclasen/gr#20]
george@george-ubuntu: sudo flatpak update
Looking for updates...
Warning: Can't find dependencies: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Problem looking for related refs: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Can't find dependencies: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Problem looking for related refs: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Can't find dependencies: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Problem looking for related refs: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Updating: org.gnome.Recipes/x86_64/master from org.gnome.Recipes-origin
Error: Failed to update org.gnome.Recipes/x86_64/master: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Updating: org.gnome.Platform.Locale/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Platform/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Recipes.Debug/x86_64/master from org.gnome.Recipes-originError: Failed to update org.gnome.Recipes.Debug/x86_64/master: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Updating: org.gnome.Recipes.Locale/x86_64/master from org.gnome.Recipes-origin
Error: Failed to update org.gnome.Recipes.Locale/x86_64/master: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Updating: org.gnome.Sdk.Debug/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Sdk.Locale/x86_64/3.22 from gnome
No updates.
Updating: org.gnome.Sdk/x86_64/3.22 from gnome
No updates.
error: One or more operations failed
george@george-ubuntu: sudo flatpak uninstall
-?                         org.gnome.Recipes.Debug
--app                      org.gnome.Recipes.Locale
--arch=                    org.gnome.Sdk
--force-remove             org.gnome.Sdk.Debug
--help                     org.gnome.Sdk.Locale
--installation             --ostree-verbose
--keep-ref                 --runtime
--no-related               --system
org.gnome.Platform         --user
org.gnome.Platform.Locale  -v
org.gnome.Recipes          --verbose
george@george-ubuntu: sudo flatpak uninstall org.gnome.Recipes
Uninstalling org.gnome.Recipes/x86_64/master

Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /home/george/.local/share
- /usr/local/share/
- /usr/share/

Uninstalling org.gnome.Recipes.Locale/x86_64/master
Uninstalling org.gnome.Recipes.Debug/x86_64/master
george@george-ubuntu: sudo flatpak uninstall org.gnome.
org.gnome.Platform         org.gnome.Sdk.Debug
org.gnome.Platform.Locale  org.gnome.Sdk.Locale
org.gnome.Sdk
george@george-ubuntu: sudo flatpak install --from https://matthiasclasen.github.io/recipes-releases/gnome-recipes.flatpakref
Installing: org.gnome.Recipes/x86_64/master
Warning: Can't find dependencies: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Warning: Problem looking for related refs: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
Installing: org.gnome.Recipes/x86_64/master from org.gnome.Recipes-origin
error: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable

**Comment by matthiasclasen** [comment]
Oh, I think I know why that is. Try now

**Comment by grousso** [comment]
Now it's ok
Thank you

**Comment by grousso** [comment]
The same again.

**Comment by matthiasclasen** [comment]
I lost the key and had to use a different one :-(

To fix your repo without uninstalling and reinstalling, you can download the new key from matthiasclasen.github.io/recipes-releases/gpgkey
and
flatpak remote-modify org.gnome.Recipes-origin --gpg-import=gpgkey
