### ISSUE TITLE
[Feature suggestion] export ingredients lists to smartphone app(s)?

### ISSUE THREAD

**Issue by ilippert** [matthiasclasen/gr#26]
I look forward to this app on Fedora soon :)

Thinking through use cases, I wondered how to get the ingredients list (to buy) into something neater than an email? e.g. import into an android app like https://f-droid.org/repository/browse/?fdfilter=shopping&fdid=privacyfriendlyshoppinglist.secuso.org.privacyfriendlyshoppinglist - I guess ingredients lists might not be standardised (yet); but it would be great to actually stick to the digital all the way to the market...
(I hope making this suggestion here is acceptable)

**Comment by matthiasclasen** [comment]
This is, in fact, a project that one of our interns will work on this summer

**Comment by matthiasclasen** [comment]
this is being worked on.
