### ISSUE TITLE
Support variable ingredients in instructions

### ISSUE THREAD

**Issue by chuckwagoncomputing** [matthiasclasen/gr#29]
It would be nice if you could have ingredient values in the instructions change as you change the serves spinner.

Most of the time there is no need to put values in the instructions, but in some recipes, an ingredient may be used two different times during the preparation in different amounts.

For example, the other day I made some flan that required melting 1 cup of sugar and mixing another 3/4 cup with the batter. If you increase the amount to be served, these amounts should of course increase as well, but there is currently no way to convey that information.

I considered diving in and adding it myself, but I noticed that your recent change to using GrIngredientsViewer broke the variable ingredients.

Are variable ingredients possible with GrIngredientsViewer? Is that something you're working on now? How can I help?

**Comment by matthiasclasen** [comment]
> It would be nice if you could have ingredient values in the instructions change as you change the serves spinner.

but...they do ?! Or at least, they do in the stable version. master lost the feature temporarily, but I just brought it back.

**Comment by chuckwagoncomputing** [comment]
Great.
