### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by Keepco** [matthiasclasen/gr#30]
Hello,

I currently ( try ) to build Gnome-Recipes, but its compilation tests fail. The compiled program itself works fine.
I build it on Exherbo Linux ( which is by no means mainstream ) - sorry if this is distribution related.

[testlog.txt](https://github.com/matthiasclasen/gr/files/1051980/testlog.txt)

**Comment by matthiasclasen** [comment]
this is with master ? tests succeed here on master...

**Comment by Keepco** [comment]
Sorry - should've included that in the original post. Seems like it's just v1.4.4 failing tests, master works fine for me

Sorry for the noise
