### ISSUE TITLE
How to use with newer GNOME version?

### ISSUE THREAD

**Issue by psukys** [matthiasclasen/gr#6]
I'm trying to install pre-built (as building step fails severely) on latest Fedora 25, which uses GNOME 3.22.2, but after installation running fails as my machine does not have 3.22 version

    error: runtime/org.gnome.Platform/x86_64/3.22 not installed

**Comment by julianrichen** [comment]
```shell
flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
flatpak install gnome org.gnome.Platform//3.22
```

http://flatpak.org/index.html#developers

**Comment by matthiasclasen** [comment]
this was answered
