### ISSUE TITLE
Can't compile newest version

### ISSUE THREAD

**Issue by Keepco** [matthiasclasen/gr#8]
Hello! 
I currently try to compile this on Gentoo (GCC 4.9.4), but it fails during make with following erros:
```gr-details-page.c: In function ‘start_or_stop_timer’:
gr-details-page.c:335:9: error: implicit declaration of function ‘gtk_popover_popdown’ [-Werror=implicit-function-declaration]
         gtk_popover_popdown (GTK_POPOVER (page->timer_popover));
         ^
gr-details-page.c:335:9: error: nested extern declaration of ‘gtk_popover_popdown’ [-Werror=nested-externs]
cc1: all warnings being treated as errors 
Makefile:857: recipe for target 'recipes-gr-details-page.o' failed
```

configure it without -Werror causes the build to fail later on with essentially the same error:
```recipes-gr-details-page.o:gr-details-page.c:function start_or_stop_timer: error: undefined reference to 'gtk_popover_popdown'
recipes-gr-edit-page.o:gr-edit-page.c:function add_ingredient: error: undefined reference to 'gtk_popover_popup'
recipes-gr-edit-page.o:gr-edit-page.c:function add_ingredient2: error: undefined reference to 'gtk_popover_popdown'
recipes-gr-image-viewer.o:gr-image-viewer.c:function file_chooser_response: error: undefined reference to 'gtk_file_chooser_get_choice'
recipes-gr-image-viewer.o:gr-image-viewer.c:function open_filechooser: error: undefined reference to 'gtk_file_chooser_add_choice'
```

**Comment by mat-mo** [comment]
On arch i get:

~/git-reops/gr ] $ ./autogen.sh
*** WARNING: I am going to run 'configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** './autogen.sh' command line.

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force -I m4 -I libgd
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:91: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by matthiasclasen** [comment]
something is amiss on your system - it is not quite a fully setup development machine. Maybe autoconf-archive ? In any case, if you can't get this to work, I can recommend trying the flatpak, which is a really convenient way to try recipes.

**Comment by mat-mo** [comment]
indeed autoconf-archive was missing, it now compiles. Thanks!

**Comment by Keepco** [comment]
So it does compile for others? I don't really want to install flatpak for just recipes

**Comment by matthiasclasen** [comment]
yeah, it does compile for others. I think I am going to close this, since I have no further insight to offer into what exactly might be missing on your system
